refactor(padding and margin utiliies): replace suffixes to use new sp…
visitscotland/vs-component-library pull request #426
Opened 2024-10-09 16:42 UTC by markup-mitchell

…acer- schema

All p and m utilities, t,b,r,l,x,y,s,e and responsive variants updated to use new spacer- schema

2024-10-10 11:33 UTC, GemmaLouise approved these changes

2024-10-11 08:18 UTC, markup-mitchell commented
@duncansanderson @mjpvs can I get your eyes on this early doors if possible?  I want to get it into v4 before it needs further reconciliation. It's tedious, but we need to get it out the way.

2024-10-11 08:23 UTC, mjpvs approved these changes

2024-10-11 08:27 UTC, duncansanderson requested changes

2024-10-11 08:27 UTC, duncansanderson commented on src/components/caption/Caption.vue
> +            padding: $spacer-100 0;
Should this be `$spacer-0` instead of `0`?

2024-10-11 08:43 UTC, merged

2024-10-11 08:58 UTC, duncansanderson commented on src/components/caption/Caption.vue
> +            padding: $spacer-100 0;
Just for consistency really, I noticed a PR the other day where 0s were changed to $spacer-0 but it's not a massive issue

2024-10-11 09:22 UTC, markup-mitchell commented
I resisted the urge to anticipate "for consistency" as a reason, but I knew it was coming! IMO consistency is a means to an end and and we should be able to articulate what the trade-off is. I don't think we currently do use `$spacer-0` in a consistent way: a quick search for `margin:` returns literally dozens of examples of `0` being used - more, in fact, than with the variable, from what I can see. 

Anyway, I hope you don't mind that I went ahead and merged on the basis of the approvals I had just to get moving. I've created a ticket (DS-537) to replace `0` with the var as a separate task.