Ds 676 list version megalinks
visitscotland/vs-component-library pull request #477
Opened 2024-12-19 10:21 UTC by chesterroberts-vs

Badges show up when new badge prop is defined, otherwise they don't show

2024-12-19 10:44 UTC, mjpvs submitted a review, later dismissed

2024-12-19 14:20 UTC, chesterroberts-vs commented
Making PR Draft: more work need in the Component Library for this ticket than previously thought.

2025-01-13 17:46 UTC, GemmaLouise requested changes

2025-01-13 17:46 UTC, GemmaLouise commented on src/components/link/Link.vue
> +        displayIcon: {
@chesterroberts-vs Not sure if this new prop is needed as we already have an option of a link with no icon which is just "default" so shouldn't need to pass in another prop?

2025-01-13 17:46 UTC, GemmaLouise commented on src/components/stretched-link-card/StretchedLinkCard.vue
> +                    :display-icon="businessSupport && isHomePage ? false : true"
I think this could be removed and instead just pass in the linkType prop in "MegalinksLinkList" as "default" which should remove any icon

2025-01-13 17:46 UTC, GemmaLouise commented on src/components/stretched-link-card/StretchedLinkCard.vue
> +        badges: {
This prop could be removed as isnt being used in the component

2025-01-14 11:45 UTC, mjpvs commented on src/components/megalinks/components/megalink-link-list/MegalinkLinkList.vue
> +        smBreakpoint() {
I was going to suggest the same thing, the only small downside on this is that if we use css the images will always be loaded, as a display: hidden image still technically gets pulled in by the browser before the css catches up. I think that's probably forgiveable for reduced complexity and having it work properly on noJs browsers, as these images should be tiny anyway

2025-01-14 15:16 UTC, GemmaLouise commented on src/components/megalinks/components/megalink-link-list/MegalinkLinkList.vue
> +        smBreakpoint() {
@mjpvs this is only going to be a temporary thing anyway as the megalinks component will be getting reviewed at some point this year to bring it in line with the system and ensure its scalable.

2025-01-14 16:00 UTC, mjpvs commented on src/components/megalinks/components/megalink-link-list/MegalinkLinkList.vue
> +        smBreakpoint() {
Aah cool, that makes sense, good to know - I just ran through these changes with Chester and we've replaced this functionality with an entirely css driven approach, but it does still depend on a quite specific flag which would be good to get rid of

2025-01-14 17:01 UTC, GemmaLouise commented on src/components/stretched-link-card/StretchedLinkCard.vue
> +                    v-else-if="(businessSupport && imagelessLayout && type === 'video')"
is imagelessLayout still in use?

2025-01-16 09:42 UTC, mjpvs commented on .storybook/preview.js
> -    tags: ["autodocs"],
Is this an intentional removal? I think it was only recently added

2025-01-16 09:47 UTC, chesterroberts-vs commented on .storybook/preview.js
> -    tags: ["autodocs"],
Yeah it was @mjpvs
For some reason my storybook doesn't load in this new version if these autodocs tags are present in any stories?
When Gemma updated Storybook to 8.4.6, she took this tag out of the other stories.
https://github.com/visitscotland/vs-component-library/commit/f134612709f197847e678b11ef577a45e5d130df

2025-01-16 09:51 UTC, mjpvs commented on .storybook/preview.js
> -    tags: ["autodocs"],
Hmm, odd that that's what's causing the issue for you, this addition in preview was supposed to be replacing it on every story by just making it the default so I think we do need one or the other. Removing it means that none of the components now has a docs page:

https://646df3398f07e38a95184dbb-cofojpughd.chromatic.com/?path=/story/accordion--default

vs

https://visitscotland.github.io/vs-component-library/?path=/docs/accordion--docs

2025-01-16 09:57 UTC, duncansanderson approved these changes

2025-01-16 09:57 UTC, duncansanderson commented on src/components/megalinks/components/megalink-link-list/MegalinkLinkList.vue
> +                .vs-stretched-link-card__img-container, .vs-stretched-link-card__video-button{
Missing a space before the `{` on these lines

2025-01-16 09:58 UTC, chesterroberts-vs commented on .storybook/preview.js
> -    tags: ["autodocs"],
I hadn't even noticed I didn't actually have the docs in my storybook at all as I was working away.
I've added it back and its working with it in now? Storybook confuses me.
Will commit with it back in.

2025-01-16 10:00 UTC, mjpvs commented on .storybook/preview.js
> -    tags: ["autodocs"],
Weird, maybe it was just some internal config issue that was out of date immediately after you updated, good that it's working now

2025-01-16 10:05 UTC, mjpvs approved these changes

2025-01-16 10:06 UTC, chesterroberts-vs commented on src/components/megalinks/components/megalink-link-list/MegalinkLinkList.vue
> +                .vs-stretched-link-card__img-container, .vs-stretched-link-card__video-button{
Added the spaces to these lines

2025-01-16 10:06 UTC, chesterroberts-vs commented on src/components/megalinks/components/megalink-link-list/MegalinkLinkList.vue
> +                .vs-stretched-link-card__img-container, .vs-stretched-link-card__video-button{
Done :)

2025-01-16 10:25 UTC, merged

2025-01-16 10:30 UTC, mjpvs commented
:tada: This PR is included in version 4.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@visitscotland/component-library/v/4.5.0)
- [GitHub release](https://github.com/visitscotland/vs-component-library/releases/tag/v4.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: